// src/statesData.js
const states = {
  "Andhra Pradesh": ["Visakhapatnam","Vijayawada","Guntur","Tirupati","Kurnool","Nellore","Anantapur","Vizianagaram","Rajahmundry","Kadapa"],
  "Arunachal Pradesh": ["Papum Pare (Itanagar)","Tawang","West Kameng (Bomdila)","East Siang (Pasighat)","Lower Subansiri (Ziro)","Changlang","Lohit (Tezu)"],
  "Assam": ["Kamrup Metro (Guwahati)","Cachar (Silchar)","Dibrugarh","Jorhat","Nagaon","Tinsukia","Barpeta","Sonitpur","Golaghat"],
  "Bihar": ["Patna","Gaya","Muzaffarpur","Bhagalpur","Darbhanga","Purnea","Nalanda","Siwan","Ara (Bhojpur)"],
  "Chhattisgarh": ["Raipur","Durg","Bilaspur","Korba","Raigarh","Rajnandgaon","Bastar (Jagdalpur)","Janjgir-Champa"],
  "Goa": ["North Goa","South Goa"],
  "Gujarat": ["Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar","Kutch (Bhuj)","Gandhinagar","Junagadh","Mehsana"],
  "Haryana": ["Gurugram","Faridabad","Panipat","Ambala","Hisar","Karnal","Rohtak","Sonipat","Panchkula","Yamunanagar"],
  "Himachal Pradesh": ["Shimla","Kangra (Dharamshala)","Mandi","Solan","Kullu","Hamirpur","Una","Sirmaur (Nahan)"],
  "Jharkhand": ["Ranchi","East Singhbhum (Jamshedpur)","Dhanbad","Bokaro","Hazaribagh","Deoghar","Giridih","Palamu (Daltonganj)"],
  "Karnataka": ["Bengaluru Urban","Mysuru","Dakshina Kannada (Mangaluru)","Belagavi (Belgaum)","Dharwad (Hubballi)","Ballari","Shivamogga","Tumakuru","Udupi"],
  "Kerala": ["Thiruvananthapuram","Ernakulam (Kochi)","Kozhikode","Thrissur","Kollam","Alappuzha","Kottayam","Palakkad","Malappuram"],
  "Madhya Pradesh": ["Bhopal","Indore","Gwalior","Jabalpur","Ujjain","Sagar","Rewa","Ratlam","Satna"],
  "Maharashtra": ["Mumbai City","Mumbai Suburban","Pune","Nagpur","Nashik","Thane","Aurangabad","Kolhapur","Solapur","Satara"],
  "Manipur": ["Imphal West","Imphal East","Churachandpur","Thoubal","Senapati","Ukhrul","Tamenglong"],
  "Meghalaya": ["East Khasi Hills (Shillong)","West Garo Hills (Tura)","Ri-Bhoi (Nongpoh)","West Jaintia Hills (Jowai)","South West Khasi Hills (Mawkyrwat)"],
  "Mizoram": ["Aizawl","Lunglei","Kolasib","Champhai","Serchhip","Mamit","Lawngtlai"],
  "Nagaland": ["Kohima","Dimapur","Mokokchung","Wokha","Zunheboto","Phek","Tuensang"],
  "Odisha": ["Khordha (Bhubaneswar)","Cuttack","Puri","Sambalpur","Sundargarh (Rourkela)","Ganjam (Berhampur)","Balasore","Mayurbhanj"],
  "Punjab": ["Amritsar","Ludhiana","Patiala","Jalandhar","Bathinda","SAS Nagar (Mohali)","Hoshiarpur","Gurdaspur"],
  "Rajasthan": ["Jaipur","Jodhpur","Udaipur","Kota","Ajmer","Alwar","Bikaner","Bhilwara","Sikar"],
  "Sikkim": ["East Sikkim (Gangtok)","South Sikkim (Namchi)","West Sikkim (Gyalshing)","North Sikkim (Mangan)"],
  "Tamil Nadu": ["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Vellore","Erode","Thoothukudi","Thanjavur"],
  "Telangana": ["Hyderabad","Ranga Reddy","Warangal","Karimnagar","Khammam","Nizamabad","Mahbubnagar","Medchal–Malkajgiri"],
  "Tripura": ["West Tripura (Agartala)","South Tripura (Udaipur)","North Tripura (Dharmanagar)","Dhalai (Ambassa)","Gomati","Khowai"],
  "Uttar Pradesh": ["Lucknow","Kanpur Nagar","Varanasi","Prayagraj (Allahabad)","Agra","Ghaziabad","Gautam Buddha Nagar (Noida)","Meerut","Gorakhpur","Bareilly"],
  "Uttarakhand": ["Dehradun","Haridwar","Nainital","Udham Singh Nagar (Rudrapur)","Pauri Garhwal","Tehri Garhwal","Almora"],
  "West Bengal": ["Kolkata","Howrah","North 24 Parganas","South 24 Parganas","Darjeeling (Siliguri)","Hooghly","Murshidabad","Nadia","Paschim Bardhaman (Durgapur)"],
  "Andaman & Nicobar Islands": ["South Andaman","North & Middle Andaman","Nicobar"],
  "Chandigarh": ["Chandigarh"],
  "Dadra & Nagar Haveli and Daman & Diu": ["Dadra & Nagar Haveli (Silvassa)","Daman","Diu"],
  "Delhi (NCT)": ["New Delhi","South Delhi","North Delhi","West Delhi","East Delhi","Central Delhi","South West Delhi","North West Delhi","Shahdara","South East Delhi"],
  "Jammu & Kashmir": ["Srinagar","Jammu","Anantnag","Baramulla","Udhampur","Kathua","Pulwama"],
  "Ladakh": ["Leh","Kargil"],
  "Lakshadweep": ["Kavaratti","Minicoy","Agatti","Amini","Andrott"],
  "Puducherry": ["Puducherry","Karaikal","Mahe","Yanam"]
};
export default states;
